core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from core import views

app_name = "core"

urlpatterns = [
    path("", TemplateView.as_view(template_name="core/main.html"), name="home"),
    path("register/", views.UserRegister.as_view(), name="register"),
    path("login/", views.UserLogin.as_view(), name="login"),
    path("logout/", views.UserLogout.as_view(), name="logout"),
    path("users/", views.UserListView.as_view(), name="users"),
    path("profile/<str:username>/", views.UserProfile.as_view(), name="profile"),
]

hr/urls.py
from rest_framework.routers import DefaultRouter

from hr.views import UserViewSet

app_name = "hr"
router = DefaultRouter()

router.register(r"users", UserViewSet, basename="users")

urlpatterns = router.urls

staffManager/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = "Storefront Admin"
admin.site.index_title = "Admin"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("djoser.urls")),
    path("auth/", include("djoser.urls.jwt")),
    path("api-auth/", include("rest_framework.urls")),
    path("hr/", include("hr.urls", namespace="hr")),
    path("", include("core.urls", namespace="core")),
    path("__debug__/", include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layouts/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="container-fluid">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'core:home' %}">Home</a>
                {% if request.user.is_authenticated %}
                    <a class="nav-item nav-link"
                       href="{% url 'core:profile' request.user.username %}">dashboard</a>
                    <a class="nav-item nav-link" href="{% url 'core:logout' %}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'core:login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'core:register' %}">Register</a>
                {% endif %}
                {% if request.user.is_superuser or request.user.staff_type == "HRA" %}
                    <a class="nav-item nav-link" href="{% url 'core:users' %}">List of Users</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>