core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from core import views

app_name = "core"

urlpatterns = [
    path("", TemplateView.as_view(template_name="core/main.html"), name="home"),
    path("register/", views.UserRegister.as_view(), name="register"),
    path("login/", views.UserLogin.as_view(), name="login"),
    path("logout/", views.UserLogout.as_view(), name="logout"),
    path("users/", views.UserListView.as_view(), name="users"),
    path("profile/<str:username>/", views.UserProfile.as_view(), name="profile"),
]

hr/urls.py
from rest_framework.routers import DefaultRouter

from hr.views import UserViewSet

app_name = "hr"
router = DefaultRouter()

router.register(r"users", UserViewSet, basename="users")

urlpatterns = router.urls

staffManager/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = "Storefront Admin"
admin.site.index_title = "Admin"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("djoser.urls")),
    path("auth/", include("djoser.urls.jwt")),
    path("api-auth/", include("rest_framework.urls")),
    path("hr/", include("hr.urls", namespace="hr")),
    path("", include("core.urls", namespace="core")),
    path("__debug__/", include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.validators import is_valid_iran_code


class User(AbstractUser):
    class Types(models.TextChoices):
        NORMAL_STAFF = "NS", "Normal Staff"
        HR_ADMIN = "HRA", "HR Admin"
        SALARY_ADMIN = "SA", "Salary Admin"

    type = models.CharField(
        _("Types"), max_length=3, choices=Types.choices, default=Types.NORMAL_STAFF
    )

    birth_date = models.DateField(_("Birth date of User"), null=True, blank=True)
    national_code = models.IntegerField(
        _("National code of User"),
        validators=[is_valid_iran_code],
        null=True,
        blank=True,
    )

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

hr/models/user.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser, Permission
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.translation import gettext_lazy as _

from hr.models.models_mixin import ModificationMixin
from hr.validators import is_valid_iran_code


class User(ModificationMixin, AbstractUser):
    username_validator = UnicodeUsernameValidator()

    class StaffTypes(models.TextChoices):
        NORMAL_STAFF = "NS", "Normal Staff"
        HR_ADMIN = "HRA", "HR Admin"
        SALARY_ADMIN = "SA", "Salary Admin"

    username = models.CharField(
        _("username"),
        max_length=150,
        unique=True,
        null=True,
        help_text=_(
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
        ),
        validators=[username_validator],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )
    email = models.EmailField(unique=True)

    staff_type = models.CharField(
        _("Types"),
        max_length=3,
        choices=StaffTypes.choices,
        default=StaffTypes.NORMAL_STAFF,
    )

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse("core:profile", args=[self.username])

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def permission_handler(self):
        if self.staff_type == self.StaffTypes.NORMAL_STAFF:
            self.set_normal_staff_permissions()
        if self.staff_type == self.StaffTypes.HR_ADMIN:
            self.set_hr_admin_permissions()
        if self.staff_type == self.StaffTypes.SALARY_ADMIN:
            self.set_hr_admin_permissions()

    def set_normal_staff_permissions(self):
        permissions_code_name = ["view_profile", "view_salary"]
        content_type = ContentType.objects.filter(model="normalstaff").first()
        permissions = Permission.objects.filter(
            codename__in=permissions_code_name, content_type=content_type
        )
        self.user_permissions.set(permissions)
        self.is_staff = True

    def set_hr_admin_permissions(self):
        permissions_code_name = ["view_profile", "change_profile", "view_salary"]
        content_type = ContentType.objects.filter(model="hradmin").first()
        permissions = Permission.objects.filter(
            codename__in=permissions_code_name, content_type=content_type
        )
        self.user_permissions.set(permissions)
        self.is_staff = True

    def set_salary_admin_permissions(self):
        permissions_code_name = [
            "view_profile",
            "view_salary",
            "change_salary",
            "add_salary",
        ]
        content_type = ContentType.objects.filter(model="salaryadmin").first()
        permissions = Permission.objects.filter(
            codename__in=permissions_code_name, content_type=content_type
        )
        self.user_permissions.set(permissions)
        self.is_staff = True


class Profile(ModificationMixin, models.Model):
    co_email = models.EmailField(_("Company email address"), blank=True)
    birth_date = models.DateField(_("Birth date of User"), null=True, blank=True)
    national_code = models.CharField(
        _("National code of User"),
        validators=[is_valid_iran_code],
        max_length=12,
        null=True,
        blank=True,
    )

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.full_name} "

    def name(self):
        return self.user.full_name

core/forms.py
from django import forms

from hr.models import Profile


class UserRegistrationForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"class": "form-control"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control"})
    )


class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"class": "form-control"})
    )


class RegisterNewEmployee(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={"class": "form-control"}))


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("co_email", "birth_date", "national_code")

core/views.py
# Create your views here.
from django.contrib import messages
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView

from core.forms import UserRegistrationForm, UserLoginForm, ProfileForm

User = get_user_model()


class UserRegister(View):
    form_class = UserRegistrationForm
    template_name = "core/register.html"

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            User.objects.create_user(data["username"], data["email"], data["password"])
            messages.success(request, "you registered successfully", "info")
            return redirect("core:home")
        return render(request, self.template_name, {"form": form})


class UserLogin(View):
    template_name = "core/login.html"
    form_class = UserLoginForm

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {"form": form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(
                request, username=data["username"], password=data["password"]
            )
            if user is not None:
                login(request, user)
                messages.success(request, "you are logged in successfully", "info")
                return redirect("core:home")
            messages.error(request, "username or password is wrong", "warning")
        return render(request, self.template_name, {"form": form})


class UserLogout(LoginRequiredMixin, View):
    @staticmethod
    def get(request):
        logout(request)
        messages.success(request, "you logged out successfully")
        return redirect("core:home")


class UserProfile(LoginRequiredMixin, View):
    template_name = "core/profile.html"
    form_class = ProfileForm

    def get(self, request, username):
        if request.user.staff_type == "HRA":
            user = get_object_or_404(User, username=username)
        else:
            if request.user.username != username:
                raise PermissionDenied
            user = get_object_or_404(User, username=request.user.username)
        return render(
            request, self.template_name, {"user": user, "form": self.form_class}
        )

    @method_decorator(permission_required("hr.change_profile", raise_exception=True))
    def post(self, request, *args, **kwargs):
        user = get_object_or_404(User, **kwargs)
        form = self.form_class(request.POST, instance=user.profile)
        if form.is_valid():
            form.save()
            messages.success(request, "your profile updated successfully", "info")
            return redirect("core:profile", user.username)


@method_decorator(
    permission_required(["hr.view_profile", "hr.change_profile"], raise_exception=True),
    name="get",
)
class UserListView(ListView):
    model = User
    queryset = User.objects.select_related("profile").all()
    template_name = "core/users.html"
    context_object_name = "user_list"
    ordering = ("id",)

core/templates/core/dashboard.html
{% extends 'base.html' %}



{% block title-head %}

    <div class="col-lg-3 text-center">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ user.username }}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>{{ user.full_name }}</li>
                    <li>{{ user.email }}</li>
                    <li>{{ user.profile.co_email }}</li>
                    <li>{{ user.get_staff_type_display }}</li>
                    <li>{{ user.profile.national_code }}</li>
                    <li>{{ user.profile.birth_date }}</li>
                </ul>
            </div>
        </div>
    </div>

{% endblock %}


{% block content %}
    <div class="col-lg-3">

    </div>

    <div class="col-lg-3 text-center">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-body">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="update" class="w-100 btn btn-lg btn-outline-primary">
                </form>
            </div>
        </div>
    </div>

{% endblock %}

core/templates/core/login.html
{% extends 'base.html' %}


{% block content %}
    <form action="" method="post" class="col-md-5">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary">
    </form>
{% endblock %}

core/templates/core/main.html
{% extends 'base.html' %}



{% block title-head %}
    <div class="text-center">
        Main Page
    </div>
{% endblock title-head %}


{% block content %}
{#    {% if request.user.is_superuser or request.user.staff_type == "HRA" %}#}
{#        <a class="nav-item nav-link" href="{% url 'core:bucket_home' %}"></a>#}
{#    {% endif %}#}
{% endblock %}

core/templates/core/profile.html
{% extends 'base.html' %}



{% block title-head %}

    <div class="col-lg-3 text-center">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ user.username }}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>{{ user.full_name }}</li>
                    <li>{{ user.email }}</li>
                    <li>{{ user.profile.co_email }}</li>
                    <li>{{ user.get_staff_type_display }}</li>
                    <li>{{ user.profile.national_code }}</li>
                    <li>{{ user.profile.birth_date }}</li>
                </ul>
            </div>
        </div>
    </div>

{% endblock %}


{% block content %}

    {% if perms.hr.change_profile %}
        <div class="col-lg-3 text-center">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-body">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="update" class="w-100 btn btn-lg btn-outline-primary">
                    </form>
                </div>
            </div>
        </div>
    {% else %}
        <div class="col-lg-3">

        </div>
    {% endif %}


{% endblock %}

core/templates/core/register.html
{% extends 'base.html' %}


{% block content %}
    <form action="" method="post" class="col-md-5">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="register">
    </form>
    <br>
{% endblock %}

core/templates/core/users.html
{% extends 'base.html' %}



{% block title-head %}
    <div class="text-center">
        Users List
    </div>
{% endblock title-head %}


{% block content %}

    <table class="table">
        <thead>
        <tr>
            <th scope="col">User id</th>
            <th scope="col">Full name</th>
            <th scope="col">Email</th>
            <th scope="col">Staff Type</th>
        </tr>
        </thead>
        <tbody>
        {% if user_list %}
            {% for user in user_list %}
                <tr>
                    <th scope="row"><a href="{{ user.get_absolute_url }}">{{ user.id }}</a></th>
                    <td>{{ user.full_name }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.get_staff_type_display }}</td>
                </tr>
            {% endfor %}
        {% else %}
            <p>There are no users in the db</p>
        {% endif %}
        </tbody>
    </table>


{% endblock %}